/**
 * Steps to publish:
 * 1. Bump lib_version inside the build.gradle of the lib module.
 * 2. Publish the SDK locally to test the artifact build process: ./gradlew clean :lib:publishLocal
 * 3. Publish to Survicate Maven by running the "Publish SDK" workflow.
 */
// https://kotlin.github.io/dokka/2.1.0/dokka-gradle-plugin/build-classic-java-and-javadoc-jars/
tasks.register('androidJavadocsJar', Jar) {
    dependsOn tasks.named("dokkaGeneratePublicationJavadoc")
    from layout.buildDirectory.dir("docs/javadoc")
    archiveClassifier.set('javadoc')
}

publishing {
    repositories {
        maven {
            name = 'survicateMaven'
            url "s3://repo.survicate.com/"

            authentication {
                // role based authentication
                awsIm(AwsImAuthentication)
            }
        }
    }

    publications {
        release(MavenPublication) {
            groupId 'com.survicate'
            artifactId 'survicate-fullstory-integration'
            version lib_version

            artifact androidJavadocsJar

            pom {
                name = "Survicate FullStory Integration"
                url = "https://github.com/Survicate/survicate-fullstory-integration-android"
                licenses {
                    license {
                        name = "MIT"
                        url = "https://raw.githubusercontent.com/Survicate/survicate-fullstory-integration-android/master/LICENSE.txt"
                        distribution = "repo"
                    }
                }
            }

            afterEvaluate {
                from components.release
            }
        }
    }
}

// Publish to Survicate S3 maven
tasks.register('publishProduction') {
    dependsOn 'publishReleasePublicationToSurvicateMavenRepository'
}

// Publish locally into ~/.m2/repository
tasks.register('publishLocal') {
    dependsOn 'publishReleasePublicationToMavenLocal'
}
